name: Docker Image CI

on:
  push:
    branches: [ "multi-arch-docker" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install buildx
      uses: crazy-max/ghaction-docker-buildx@v1
      with:
        version: latest
    - name: Login to Github registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
    - name: Build the Docker image
      run: |
        docker buildx build --push \
             --tag ghcr.io/${{ github.repository }} \
             --platform linux/arm64,linux/amd64,linux/arm/v6,linux/arm/v7,linux/386 .
