name: Docker Image CI

on:
  push:
    branches: [ "multi-arch-docker" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install buildx
      uses: crazy-max/ghaction-docker-build@v1
      with:
        version: latest
    - name: Login to GH-Container registry
      uses: docker/login-action@v2.1.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the Docker image
      run: docker buildx build --push \
             --tag philskat/crontab-ui:latest
             --platform linux/arm64,linux/amd64,linux/arm/v6,linux/arm/v7,linux/386 .
